### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by cfbermudez** [mikegedelman/atom-force#4]
[Enter steps to reproduce:]

1. Packages
2. atom-force
3. Add/Change Force.com Nature
4. In Text Field write any Path

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-force](https://github.com/mikegedelman/atom-force) package 0.3.4

### Stack Trace

Uncaught TypeError: string.indexOf is not a function

```
At C:\Users\cbermudez\.atom\packages\atom-force\node_modules\fuzzaldrin\lib\scorer.js:60

TypeError: string.indexOf is not a function
    at Object.exports.score (/packages/atom-force/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at module.exports (/packages/atom-force/node_modules/fuzzaldrin/lib/filter.js:25:24)
    at filter (/packages/atom-force/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at Selector.module.exports.SelectListView.populateList (/packages/atom-force/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
    at /packages/atom-force/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```

### Commands

```
     -8:50.7.0 atom-force:addForceNature (input.hidden-input)
     -8:45.2.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:18.9.0 atom-force:addForceNature (input.hidden-input)
     -8:12.6.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -8:03.6.0 atom-force:addForceNature (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -5:57.7.0 window:increase-font-size (input.hidden-input)
     -5:34.9.0 atom-force:addForceNature (input.hidden-input)
     -5:12.6.0 settings-view:uninstall-packages (input.hidden-input)
  4x -4:59.2.0 core:move-left (input.hidden-input)
     -4:58.2.0 core:backspace (input.hidden-input)
     -2:37.6.0 atom-force:toggle (div.package-detail.panels-item)
     -2:26.8.0 atom-beautify:beautify-editor (div.package-detail.panels-item)
  3x -2:19.6.0 atom-force:addForceNature (div.package-detail.panels-item)
     -0:30.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-force 0.3.4 
atom-maven 1.1.0 
busy-signal 1.3.0 
language-salesforce 0.6.0 
linter 1.11.23 
MavensMate-Atom 1.0.10 
pretty-json 1.6.1 
xml-formatter 0.10.0 
```

**Comment by DannyK89** [comment]
I'm having the same issue.
