### ISSUE TITLE
Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by rmx90210** [mikegedelman/atom-force#7]
[Enter steps to reproduce:]

1. Edit a file and save. Note: I've only seen this with static resources so far; my regular Apex classes seem to be saving fine.

**Atom**: 1.22.1 ia32
**Electron**: 1.6.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-force](https://github.com/mikegedelman/atom-force) package 0.3.6

### Stack Trace

Uncaught TypeError: callback is not a function

```
At C:\Users\robert.martin\.atom\packages\atom-force\node_modules\nforce-tooling\index.js:223

TypeError: callback is not a function
    at /packages/atom-force/node_modules/nforce-tooling/index.js:223:26
    at Object.resolve (/packages/atom-force/node_modules/nforce/lib/promises.js:25:20)
    at processResponse (/packages/atom-force/node_modules/nforce/index.js:1011:25)
    at Request._callback (/packages/atom-force/node_modules/nforce/index.js:1069:7)
    at Request.self.callback (/packages/atom-force/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at /packages/atom-force/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at /packages/atom-force/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -1:02.3.0 intentions:highlight (input.hidden-input)
     -1:02.3.0 core:save (input.hidden-input)
     -0:57.5.0 atom-force:toggle (input.hidden-input)
     -0:46.9.0 intentions:highlight (input.hidden-input)
     -0:46.7.0 core:save (input.hidden-input)
     -0:33.8.0 intentions:highlight (input.hidden-input)
     -0:33.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-force 0.3.6 
busy-signal 1.4.3 
intentions 1.1.5 
language-batch 0.4.0 
language-salesforce 0.6.0 
language-vue 0.23.1 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-ui-default 1.6.10 
react 0.17.0 
script 3.17.3 
sort-lines 0.18.0 
```

**Comment by mikegedelman** [comment]
Published `v0.3.7` which should fix this
